[ai_model]
ai = "Groq"
api_key = ""
chat_rounds = 20
model = "llama3-8b-8192"
max_tokens = 4096
chat_prompt = "请使用中文回复我。如果发现我的语句不通顺，先显式纠正，再根据纠正后的语句回答，注意区分口语和书面语。尽可能使用更加人性化的语气。"

[display]
language = ""
font_size = "15"
theme = "深色模式"