[openai]
api_key = ""
chat_rounds = 35
model = "gpt-3.5-turbo"
max_tokens = 1080
chat_prompt = "默认使用中文回复我。如果发现我的语句不通顺，先显示纠正，再根据纠正后的语句回答。"

[aliyun]
app_key = ""
access_key_id = ""
access_key_secret = ""
