[ai_model]
ai = "OpenAI"
api_key = ""
chat_rounds = 30
model = "gpt-4-turbo"
max_tokens = 4096
chat_prompt = "请中文回复我。如果发现我的语句不通顺，先显示纠正，再根据纠正后的语句回答。在回答我的时候尽量使用emoji，尽可能使用更加人性化的语气。"

[aliyun]
app_key = ""
access_key_id = ""
access_key_secret = ""

