# Form implementation generated from reading ui file 'C:\Users\13677\Desktop\graduation_project\GPTalks\ui\changepwd_diglog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_changepwd_Dialog(object):
    def setupUi(self, changepwd_Dialog):
        changepwd_Dialog.setObjectName("changepwd_Dialog")
        changepwd_Dialog.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(changepwd_Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=changepwd_Dialog)
        self.lineEdit.setStyleSheet("font: 20pt \"Microsoft YaHei UI\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=changepwd_Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=changepwd_Dialog)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=changepwd_Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_currentpwd = QtWidgets.QLineEdit(parent=changepwd_Dialog)
        self.lineEdit_currentpwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_currentpwd.setObjectName("lineEdit_currentpwd")
        self.horizontalLayout_3.addWidget(self.lineEdit_currentpwd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=changepwd_Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_newpwd = QtWidgets.QLineEdit(parent=changepwd_Dialog)
        self.lineEdit_newpwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_newpwd.setObjectName("lineEdit_newpwd")
        self.horizontalLayout_4.addWidget(self.lineEdit_newpwd)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=changepwd_Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_newpwd2 = QtWidgets.QLineEdit(parent=changepwd_Dialog)
        self.lineEdit_newpwd2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_newpwd2.setObjectName("lineEdit_newpwd2")
        self.horizontalLayout_5.addWidget(self.lineEdit_newpwd2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=changepwd_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(changepwd_Dialog)
        self.buttonBox.accepted.connect(changepwd_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(changepwd_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(changepwd_Dialog)

    def retranslateUi(self, changepwd_Dialog):
        _translate = QtCore.QCoreApplication.translate
        changepwd_Dialog.setWindowTitle(_translate("changepwd_Dialog", "修改密码"))
        self.lineEdit.setText(_translate("changepwd_Dialog", "重置密码"))
        self.label.setText(_translate("changepwd_Dialog", "用 户 名"))
        self.label_2.setText(_translate("changepwd_Dialog", "当前密码"))
        self.label_3.setText(_translate("changepwd_Dialog", "新 密 码"))
        self.label_4.setText(_translate("changepwd_Dialog", "新 密 码"))
