on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'V*' # Push events to matching V*, i.e. V1.0, V20.15.10

name: Create Release

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build
        run: |
          pyinstaller --onefile --windowed main.py -n GPTalks.exe
          cp config.toml dist/
          cp ai_model.json dist/
          cp LICENSE dist/
          cd dist/
          zip GPTalks.zip ./*
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            dist/GPTalks.zip
